### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by 2E0PGS** [kaihendry/natalian#3]
I see dabase has a feed although I would of expected it under `/feed`, `/rss` or `rss.xml` but I found it under `index.xml` which is fine I guess.

Anyway I cannot seem to find a RSS feed for https://natalian.org does one exsist? Possibly not since it's not build with Hugo like dabase is?

**Comment by kaihendry** [comment]
Thanks for your interest! =)

I only adverstise an atom feed for Natalian https://natalian.org/index.atom in the page source. Your feed reader should grok it **link rel="alternate" type="application/atom+xml" title="Atom feed"** IIUC It's generated by https://github.com/kaihendry/blog/tree/master/feeds

Else do please take a look at https://github.com/kaihendry/hendry.iki.fi/blob/master/Makefile
